env:
  browser: true
  commonjs: true
  es2021: true
  mocha: true
extends: airbnb-base
overrides:
  - files:
      - "test/*.js"
    rules:
      func-names: off
parserOptions:
  ecmaVersion: latest
rules:
  max-len:
    - 1
    - 200

  # TODO: remove after alignment effort with the original package
  no-console: off
  no-param-reassign: off
  no-multi-assign: off
  func-names: off
  no-underscore-dangle: off
  no-loop-func: off
  no-use-before-define: off
  prefer-spread: off
  prefer-const: off
  no-buffer-constructor: off
  import/order: off
  no-shadow: off
  no-unused-expressions: off
  prefer-destructuring: off
  # END
